### ISSUE TITLE
ConvertTo-PnPClientSidePage : One or more errors occurred. At line:1 char:1

### ISSUE THREAD

**Issue by kunj-sangani** [SharePoint/sp-dev-modernization#121]
I am facing the below issue can you please help on this 

ConvertTo-PnPClientSidePage : One or more errors occurred.
At line:1 char:1
+ ConvertTo-PnPClientSidePage -Identity "Home.aspx"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPClientSidePage], AggregateException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage 

Result of Get-PnPException is below

Message          : One or more errors occurred.
Stacktrace       :    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
                      at OfficeDevPnP.Core.Pages.ClientSidePage.AvailableClientSideComponents(String name)
                      at
                   SharePointPnP.Modernization.Framework.Cache.CacheManager.GetClientSideComponents(ClientSidePage
                   page)
                      at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1
                   webParts)
                      at SharePointPnP.Modernization.Framework.Transform.PageTransformator.Transform(PageTransformation
                   Information pageTransformationInformation)
                      at SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 1

Result of get-module -Name SharePointPnPPowerShellOnline is below

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     3.8.1904.0 SharePointPnPPowerShellOnline       {Add-PnPAlert, Add-PnPApp, Add-PnPClientSidePage, Add-PnPC...

**Comment by kunj-sangani** [comment]
It started working without any code changes 
Thanks
