### ISSUE TITLE
PnP Cmdlet -Connection Param Issue

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#144]
#### Category

- [X] Bug
- [ ] Enhancement

#### Problem Area

- [ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
- [X] Page Transformation: Error during the use of page transformation from PnP PowerShell
- [ ] Page Transformation: Error during the use of page transformation from .Net
- [ ] Page Transformation: Page is not looking correct after transformation
- [ ] Modernization Scanner: something went wrong...
- [X] Issue between the computer and the chair

#### Expected or Desired Behavior

When using the cmdlet ConvertTo-PnPClientSitePage in a scenario where i'm using the -connection param to specify multiple sources sites. 

I would expect the Connection parameter would be the source context

#### Observed Behavior

I hit a validation with the message: 

Get-PnPException output:
```
Message          : Publishing page transformation is only supported when transformating into another site collection.
                   Use the -TargetWebUrl to specify a modern target site.
Stacktrace       :    at SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 72
```

#### Steps to Reproduce

e.g in multi-lingual scenario:
* English Site
* Welsh Site
* Same Page Name in both

* Connect to sites (English/Welsh)

```powershell
$engConn = Connect-PnPOnline $engSourceUrl -ReturnConnection
$welConn = Connect-PnPOnline $welSourceUrl -ReturnConnection

```
* For each English page

```powershell
# Transform English
ConvertTo-PnPClientSidePage -PublishingPage -Identity $englishPageName -TargetWebUrl $englishCommSite -PageLayoutMapping $mapping - LogFolder "C:\temp\logs" -LogType File -DontPublish -SkipItemLevelPermissionCopyToClientSidePage -Connection $engConn

# Transform Welsh
ConvertTo-PnPClientSidePage -PublishingPage -Identity $englishPageName -TargetWebUrl $welshCommSite -PageLayoutMapping $mapping - LogFolder "C:\temp\logs" -LogType File -DontPublish -SkipItemLevelPermissionCopyToClientSidePage -Connection $welConn
```

**Comment by jansenbe** [comment]
Hi @pkbullock ,

I'm not able to simulate this issue...The code that throws the error is this:

```Csharp
            // Publishing specific validation
            if (this.PublishingPage && string.IsNullOrEmpty(this.TargetWebUrl))
            {
                throw new Exception($"Publishing page transformation is only supported when transformating into another site collection. Use the -TargetWebUrl to specify a modern target site.");
            }
```
So looking your script my assumption is that one of the 2 used targetweburl variables are not correctly set. Can you cross check that?
