### ISSUE TITLE
Item level permissions broken (dev build)

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#212]
#### Category

- [X] Bug
- [ ] Enhancement

#### Problem Area

ASP.NET Unit Tests -I get errors context has changed when running tests for transforming between Publishing Site Classic SPO to Modern SPO. 

#### Expected or Desired Behavior

Should work, but getting this error below.

@jansenbe - I am investigating some other issues with transforming from client collecting data atm, just wondering if you have capacity to see if this also breaks in your test rig?

The page doesn't have broken permission inheritance in tests but still get the below errors.

#### Observed Behavior

```
ERROR: Summary Message: A critical error occurred - transformation did not complete 
	 Source: System.String Transform(SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformationInformation), Error: The object is used in the context different from the one associated with the object.
ERROR: Stack Trace:    at Microsoft.SharePoint.Client.ClientAction.CheckActionParameterInContext(ClientRuntimeContext context, Object value)
   at Microsoft.SharePoint.Client.ClientAction.CheckActionParametersInContext(ClientRuntimeContext context, Object[] values)
   at Microsoft.SharePoint.Client.ObjectPathMethod..ctor(ClientRuntimeContext context, ObjectPath parent, String methodName, Object[] parameters)
   at Microsoft.SharePoint.Client.RoleAssignmentCollection.Add(Principal principal, RoleDefinitionBindingCollection roleBindings)
   at SharePointPnP.Modernization.Framework.Transform.BasePageTransformator.ApplyItemLevelPermissions(Boolean hasTargetContext, ListItem item, ListItemPermission lip, Boolean alwaysBreakItemLevelPermissions) in C:\Git\contrib\capa-sp-dev-modern\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Framework\Transform\BasePageTransformator.cs:line 217
   at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation) in C:\Git\contrib\capa-sp-dev-modern\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Framework\Publishing\PublishingPageTransformator.cs:line 492
```

**Comment by jansenbe** [comment]
@pkbullock : Let me test this. So you're testing from publishing portal in SPO to modern site in SPO...right?

**Comment by pkbullock** [comment]
Yeap, in my reproduction of the other issues the unit tests were failing at this point, just want to make sure that I haven’t introduced a bug.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jansenbe** [comment]
I can repro this when there are custom permissions set on the classic publishing page. Will debug and fix.

**Comment by jansenbe** [comment]
@pkbullock : Fixed, assume this actually never really worked. The implementation will assign user accounts to the target page, groups are only assigned when the group already exists in the target site collection.
