### ISSUE TITLE
SP2010 ConvertTo Command Error

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#232]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Should transform.

#### Observed Behavior

Getting error in transforming pages:

```
_Root element is missing.   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at SharePointPnP.Modernization.Framework.Pages.BasePage.LoadPublishingPageFromWebServices(String fullUrl)
   at SharePointPnP.Modernization.Framework.Pages.PublishingPageOnPremises.Analyze(PageLayout publishingPageTransformationModel)
   at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)_ 

```

Please can you assign to me...

**Comment by pkbullock** [comment]
ok this one test case fail, majority of others are working... 😊

**Comment by pkbullock** [comment]
The above sample shows how to convert to on-premises for those that want to try it, please keep this issue open until i see what is causing the above error.

**Comment by jansenbe** [comment]
Seems like either unexpected output coming from calling the 2010 web services or something missing in the content to XML cleanup code.

For others: this bug only can occur when you're modernizing SP2010 publishing pages.

**Comment by jansenbe** [comment]
PR (#235) merged, closing this issue
