### ISSUE TITLE
Apply-PnPTenantTemplate : Access Denied

### ISSUE THREAD

**Issue by brettly80** [SharePoint/sp-dev-modernization#29]
I'm having an issue applying the PNP template.
I'm a global admin, I have an app store, I have the latest files, 
Any ideas?

Message          : {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}
Stacktrace       :    at OfficeDevPnP.Core.ALM.AppManager.<BaseAddRequest>d__39.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at OfficeDevPnP.Core.ALM.AppManager.<AddAsync>d__5.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at OfficeDevPnP.Core.ALM.AppManager.Add(Byte[] file, String filename, Boolean overwrite, AppCatalogScope scope, Int32 timeoutSeconds)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.TenantHelper.ProcessApps(Tenant tenant, ProvisioningTenant provisioningTenant, FileConnectorBase connector, TokenParser parser,
                   PnPMonitoredScope scope, ProvisioningTemplateApplyingInformation applyingInformation, ProvisioningMessagesDelegate messagesDelegate)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHierarchyTenant.ProvisionObjects(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId, TokenParser parser,
                   ProvisioningTemplateApplyingInformation applyingInformation)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyProvisioningHierarchy(Tenant tenant, ProvisioningHierarchy hierarchy, String sequenceId,
                   ProvisioningTemplateApplyingInformation provisioningInfo)
                      at SharePointPnP.PowerShell.Commands.Provisioning.Tenant.ApplyTenantTemplate.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 1

**Comment by brettly80** [comment]
That worked!! This is an environment I inherited. I checked the permissions on the main site collection. I don't know why I didn't think about checking the app catalog. Cheers!!
