### ISSUE TITLE
"String cannot be of zero length. Parameter name: oldValue" thrown as an Inner Exception when transforming a page.

### ISSUE THREAD

**Issue by GCamilleri** [SharePoint/sp-dev-modernization#30]
Title says it all. Looks like it's trying to replace a token in the URI for the new page? This happens on many pages on the site I'm working with. 

**Outer exception (top level of this hidden, it's just Main() in program.cs on my end):**
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.ExecuteMethod(Object functionClassInstance, FunctionDefinition functionDefinition, MethodInfo methodInfo)
   at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.Process(WebPart& webPartData, WebPartEntity webPart)
   at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1 webParts)
   at SharePointPnP.Modernization.Framework.Transform.PageTransformator.Transform(PageTransformationInformation pageTransformationInformation)

**Inner Exception:** 
   at System.String.ReplaceInternal(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue)
   at SharePointPnP.Modernization.Framework.Functions.BuiltIn.ListAddWebRelativeUrl(Guid listId)

**Comment by jansenbe** [comment]
Hi @GCamilleri ,

Thanks for reporting this. Did some more testing and this indeed is a bug when transforming pages on the root site collection of your tenant. This has been fixed in https://github.com/SharePoint/sp-dev-modernization/commit/4f2e2b7421ad92602f290cfa1590021d5c2a5ee1 and will end up in the 1.0.1901.1 version which I'll release in the coming days. 

Transforming pages in other site collections should not be impacted by this, it's just the root web of the root site collection that's impacted.

**Comment by jansenbe** [comment]
Hi @GCamilleri ,

Version 1.0.1901.1 has been released on Nuget. Closing this issue now.

**Comment by GCamilleri** [comment]
Excellent! Thanks.
