### ISSUE TITLE
Exception when StoredCertificate used

### ISSUE THREAD

**Issue by Forket** [SharePoint/sp-dev-modernization#387]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[X] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
Script should use certificate previously saved to CertStore (user or comp) when starting tool from cmd
#### Observed Behavior

```console
Unhandled Exception: System.Exception: Clonflicting security parameters provided.
   at SharePoint.Modernization.Scanner.Core.Options.AuthenticationTypeProvided() in C:\github\sp-dev-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Scanner.Core\Options.cs:line 167
   at SharePoint.Modernization.Scanner.Core.ScanJob..ctor(Options options, String jobName, String jobVersion) in C:\github\sp-dev-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Scanner.Core\ScanJob.cs:line 67
   at SharePoint.Modernization.Scanner.Core.ModernizationScanJob..ctor(Options options) in C:\github\sp-dev-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Scanner.Core\ModernizationScanJob.cs:line 68
   at SharePoint.Modernization.Scanner.Program.Main(String[] args)

```

#### Steps to Reproduce
```PowerShell
C:\SharePoint.Modernization.Scanner.exe --Mode "Full" --Threads 10 --DateFormat "d/M/yyyy" --Urls "https://<tenantname>.sharepoint.com/sites/test*" --SkipReport --ClientId <ClientId> --StoredCertificate "My|LocalMachine|C88C0558330B6644B9B545FEC32296090EA25B81"
```

**Comment by jansenbe** [comment]
On top of my head: think you also need to specify the azure tenant via the --AzureTenant option. Will give this a try later tomorrow in case this is not the fix

**Comment by Forket** [comment]
Thanks for quick answer. Just tried addin ``` --AzureTenant``` option and got another error.BUT, here is some confusing definition: what does script required for ``` --AzureTenant``` option:
- full tenant domain name taken from Azure AD? In my case, i have my custom primary domain **mydomain.com**
- full host name used for SharePoint Online, e.g.: **<tenantname>.sharepoint.com**
- just tenant name **<tenantname>**

I've tried all 3 options so my full command looked like this:
```batch
λ  C:\SharePoint.Modernization.Scanner.exe --Mode "Full" --Threads 10 --DateFormat "d/M/yyyy" --Urls "https://<tenantname>.sharepoint.com/sites/test*" --SkipReport --ClientId "<ClientId>" --StoredCertificate "My|LocalMachine|C88C0558330B6644B9B545FEC32296090EA25B83" --AzureTenant "<tenantname>"
```
```batch
λ  C:\SharePoint.Modernization.Scanner.exe --Mode "Full" --Threads 10 --DateFormat "d/M/yyyy" --Urls "https://<tenantname>.sharepoint.com/sites/test*" --SkipReport --ClientId "<ClientId>" --StoredCertificate "My|LocalMachine|C88C0558330B6644B9B545FEC32296090EA25B83" --AzureTenant "<tenantname>.sharepoint.com"
```
```batch
λ  C:\SharePoint.Modernization.Scanner.exe --Mode "Full" --Threads 10 --DateFormat "d/M/yyyy" --Urls "https://<tenantname>.sharepoint.com/sites/test*" --SkipReport --ClientId "<ClientId>" --StoredCertificate "My|LocalMachine|C88C0558330B6644B9B545FEC32296090EA25B83" --AzureTenant "mycustomdomain.com"
```
and as result **same error**:
```console
Unhandled Exception: System.Security.Cryptography.CryptographicException: Keyset does not exist

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.GetAsymmetricAlgorithm(String algorithm, Boolean privateKey)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.CryptographyHelper.SignWithCertificate(String message, X509Certificate2 certificate)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.ClientCreds.JsonWebToken.Sign(IClientAssertionCertificate credential, Boolean sendX5C)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.ClientCreds.ClientKey.AddToParameters(IDictionary`2 parameters)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBrokerAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by Forket** [comment]
Performed one more test, as I really think that here is issue related to case when we use ```--storedcertificate``` argument. So i decided to make a try with ```--certificatepfx``` and ```--certificatepfxpassword``` arguments instead. Final command looked like this:
```batch
λ  C:\SharePoint.Modernization.Scanner.exe --Mode "Full" --Threads 10 --DateFormat "d/M/yyyy" --Urls "https://<tenantname>.sharepoint.com/sites/test*" --SkipReport --ClientId "<ClientId>" --AzureTenant "<mycustomdomain.com>" --certificatepfx "<path to pfx file>" --certificatepfxpassword "<pfx certificate password as plaintext>"
```
And there were no error. Scanner run completed with success. So, we can see that issue is somehow related to ```--storedcertificate``` arg

By the way, self-answered my question what i should pass as value for ```--AzureTenant``` argument :) So I believe in doc you should clearly write that this is value should be taken from AzureAD. Because (as end-user opinion) at first try we (end-users) thinking in SharePoint context and trying to use **tenantname.sharepoint.com** value which is not correct :)

```batch
λ  C:\SharePoint.Modernization.Scanner.exe --Mode "Full" --Threads 10 --DateFormat "d/M/yyyy" --Urls "https://<tenantname>.sharepoint.com/sites/test*" --SkipReport --ClientId "<ClientId>" --StoredCertificate "My|LocalMachine|C88C0558330B6644B9B545FEC32296090EA25B83" --AzureTenant "mycustomdomain.com"
```

**Comment by jansenbe** [comment]
Thanks for the feedback @Forket. 

Good you got it work via the pfx file. This then implies that it should also work using a locally stored cert. You used `My|LocalMachine|C88C0558330B6644B9B545FEC32296090EA25B81`, so the cert is in the local machine cert store. This works but keep in mind that you either need to run the scanner as local admin or alternatively grant the account you run the scanner with permissions to read the private key of the cert. When storing in CurrentUser the current user always has access.

About the tenant id: I'll create a back log entry to update the docs to make that more clear.

**Comment by Forket** [comment]
Thanks for clarification. You are right. Tested under admin and works well.
Believe, such information should also be added to docs as some Notice. This would prevent further issues creation  like this one. :)

**Comment by Forket** [comment]
Work perfect with cert saved in CurrentUser cert store. Will close issue. Thanks for clarification
