### ISSUE TITLE
Exception when  --exportpaths arg used

### ISSUE THREAD

**Issue by Forket** [SharePoint/sp-dev-modernization#388]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[X] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
When  --exportpaths arg key used, with folder path passed as value:
```console
--exportpaths "C:\Temp"
```
it is expected that scanner would use this folder for csv/xlsx output
#### Observed Behavior
error in console
```console
λ  C:\SharePoint.Modernization.Scanner.exe --mode "Full" --threads 10 --dateformat "d/M/yyyy" --exportpaths "C:\Temp" --urls "https://<tenantid>.sharepoint.com/sites/test*" --skipreport --clientid <ClientId> --storedcertificate "My|LocalMachine|C88C0558330B6644B9B545FEC32296090EA25B83"

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: Table can't be null
   at OfficeOpenXml.ExcelRangeBase.LoadFromDataTable(DataTable Table, Boolean PrintHeaders)
   at SharePoint.Modernization.Scanner.Core.Reports.Generator.InsertTableData(ExcelTable table, DataTable data) in C:\github\sp-dev-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Scanner.Core\Reports\Generator.cs:line 1291
   at SharePoint.Modernization.Scanner.Core.Reports.Generator.CreateGroupifyReport(List`1 reportStreams) in C:\github\sp-dev-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Scanner.Core\Reports\Generator.cs:line 1262
   at SharePoint.Modernization.Scanner.Program.Main(String[] args)
```
#### Steps to Reproduce
```console
λ  C:\SharePoint.Modernization.Scanner.exe --mode "Full" --threads 10 --dateformat "d/M/yyyy" --exportpaths "C:\Temp" --urls "https://<tenantid>.sharepoint.com/sites/test*" --skipreport --clientid <ClientId> --storedcertificate "My|LocalMachine|C88C0558330B6644B9B545FEC32296090EA25B83"
```

**Comment by jansenbe** [comment]
ExportPaths has a different purpose: it's meant to provide paths with scanner results so that the scanner can read these individual scan results and combine them in the xlsx based reports. The actual scanner output will always be created in a sub folder of the folder hosting the scanner executable, there's no option to change that.

If this clarifies things, then feel free to close the issue. If you need more or can't work with the scan output in the current location then please let me know.

**Comment by Forket** [comment]
Expected such answer, but was thinking it's not true :)
As for output - in my exact case it really makes sense as scanner is used as part of PowerShell module. And in this case scanner would output data to folder where PSModule is located (could cause issues in case if module would be in some system directory). Thus, if it's possible to have ```--Output``` arg - that would be helpful.
![image](https://user-images.githubusercontent.com/6735288/70567156-ae812e00-1b95-11ea-9d92-14d71e6988a2.png)

**Comment by jansenbe** [comment]
The scanner core is isolated in it's separate library, you could potentially wrap it in a PS cmdlet or in your .Net solution. Doing this will give you the flexibility to choose where the scan output is placed. See https://github.com/SharePoint/sp-dev-modernization/blob/dev/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Scanner/Program.cs for an example on how the core scanning is used. Would such an approach work for you?

**Comment by Forket** [comment]
@jansenbe, theoretically understand your suggestion, but maybe could you point me to right direction. Because I understand that I can redirect scanner output to file using ```Out-File``` , but in this case we are not talking about redirecting console output, but redirecting FILES generated by scaner to some other folder.  PS doesn't have something like ```Out-Folder``` or something like this. 
Maybe could you more clearly point me to correct approach using PS, not .Net solution.
Thanks in advance.

**Comment by Forket** [comment]
Here is how my PS Function looks like :)
```PowerShell
function Invoke-SPModernizationScanner {
    [CmdletBinding( DefaultParameterSetName = "Certificate")]
    param (

        [Parameter( ValueFromPipeline, ValueFromPipelineByPropertyName, ParameterSetName = "Certificate" )]
        [Parameter( ValueFromPipeline, ValueFromPipelineByPropertyName, ParameterSetName = "CertificateFile" )]
        [Parameter( ValueFromPipeline, ValueFromPipelineByPropertyName, ParameterSetName = "ClientSecret" )]
        [Parameter( ValueFromPipeline, ValueFromPipelineByPropertyName, ParameterSetName = "Credential" )]
        [ValidateNotNullOrEmpty()]
        [ValidateScript( {
                ([uri]( $_ -replace "\*", "" )).Host -eq "$( $Global:SPOM_Config.TenantName ).sharepoint.com"
            })]
        [Uri[]]
        $Urls,

        # Parameter help description
        [Parameter(Mandatory, ParameterSetName = "Certificate")]
        [Parameter(Mandatory, ParameterSetName = "CertificateFile")]
        [Parameter(Mandatory, ParameterSetName = "ClientSecret")]
        [string]
        $ClientId,

        # Parameter help description
        [Parameter(Mandatory, ParameterSetName = "Certificate")]
        [string]
        $Thumbprint,

        # Parameter help description
        [Parameter(Mandatory, ParameterSetName = "CertificateFile")]
        [ValidateScript( {
                $_ | Test-Path -PathType Leaf -Include *.pfx
            })]
        [string]
        $CertificatePFX,

        # Parameter help description
        [Parameter(Mandatory, ParameterSetName = "CertificateFile")]
        [SecureString]
        $CertificatePFXPassword,

        # Parameter help description
        [Parameter(ParameterSetName = "ClientSecret")]
        [SecureString]
        $ClientSecret,


        # Parameter help description
        [Parameter(Mandatory, ParameterSetName = "Credential")]
        [PSCredential]
        $Credential,

        # Parameter help description
        [Parameter(ParameterSetName = "Certificate")]
        [Parameter(ParameterSetName = "CertificateFile")]
        [Parameter(ParameterSetName = "ClientSecret")]
        [Parameter(ParameterSetName = "Credential")]
        [string]
        [ValidateSet(
            "Full",
            "GroupifyOnly",
            "ListOnly",
            "PageOnly",
            "PublishingOnly",
            "PublishingWithPagesOnly",
            "WorkflowOnly",
            "InfoPathOnly",
            "BlogOnly"
        )]
        $Mode = "Full",

        # Parameter help description
        [Parameter(ParameterSetName = "Certificate")]
        [Parameter(ParameterSetName = "CertificateFile")]
        [Parameter(ParameterSetName = "ClientSecret")]
        [Parameter(ParameterSetName = "Credential")]
        [int]
        [ValidateRange(1, 20)]
        $Threads = 10,

        # Parameter help description
        [Parameter(ParameterSetName = "Certificate")]
        [Parameter(ParameterSetName = "CertificateFile")]
        [Parameter(ParameterSetName = "ClientSecret")]
        [Parameter(ParameterSetName = "Credential")]
        [Bool]
        $SkipUsageInformation = $false,

        # Parameter help description
        [Parameter(ParameterSetName = "Certificate")]
        [Parameter(ParameterSetName = "CertificateFile")]
        [Parameter(ParameterSetName = "ClientSecret")]
        [Parameter(ParameterSetName = "Credential")]
        [Bool]
        $SkipUserInformation = $false,

        # Parameter help description
        [Parameter(ParameterSetName = "Certificate")]
        [Parameter(ParameterSetName = "CertificateFile")]
        [Parameter(ParameterSetName = "ClientSecret")]
        [Parameter(ParameterSetName = "Credential")]
        [Bool]
        $SkipListsOnlyBlockedByOOBReasons = $false,

        # Parameter help description
        [Parameter(ParameterSetName = "Certificate")]
        [Parameter(ParameterSetName = "CertificateFile")]
        [Parameter(ParameterSetName = "ClientSecret")]
        [Parameter(ParameterSetName = "Credential")]
        [switch]
        $SkipReport,

        # Parameter help description
        [Parameter(ParameterSetName = "Certificate")]
        [Parameter(ParameterSetName = "CertificateFile")]
        [Parameter(ParameterSetName = "ClientSecret")]
        [Parameter(ParameterSetName = "Credential")]
        [Bool]
        $DisableTelemetry = $false,

        # Parameter help description
        [Parameter(ParameterSetName = "Certificate")]
        [Parameter(ParameterSetName = "CertificateFile")]
        [Parameter(ParameterSetName = "ClientSecret")]
        [Parameter(ParameterSetName = "Credential")]
        [ValidateSet(
            , "d/M/yyyy"
            , "M/d/yyyy"
        )]
        $DateFormat = "M/d/yyyy",

        # Parameter help description
        [Parameter(ParameterSetName = "Certificate")]
        [Parameter(ParameterSetName = "CertificateFile")]
        [Parameter(ParameterSetName = "ClientSecret")]
        [Parameter(ParameterSetName = "Credential")]
        [ValidateScript( {
                ($_ | Where { !(Test-Path $_ -PathType Container) } | Measure).Count -eq 0
            })]
        [string[]]
        $ExportPaths,

        # Parameter help description
        [Parameter(ParameterSetName = "Certificate")]
        [Parameter(ParameterSetName = "CertificateFile")]
        [Parameter(ParameterSetName = "ClientSecret")]
        [Parameter(ParameterSetName = "Credential")]
        [ValidateScript( {
                ($_ | Where { !(Test-Path $_ -PathType Container) } | Measure).Count -eq 0
            })]
        [string[]]
        $OutputFolder = (Get-Location).Path

    )

    begin {

        Test-RequiredTools -Tools @("SPModernizationScanner") -ForceError | Out-Null

        # TODO: Also implement additional check if there are any PSDefaultParameters which are not related to passed ParameterSetName. For example, in case if in config er have defined auth as certificate, but function is invoked with credentials.

    }

    process {

    }

    end {

        # INFO: https://gist.github.com/magnetikonline/f880b0cb063c54568ade7073f935bbd1
        $cmdArgList = @(
            "--Mode", $Mode,
            "--Threads", $Threads,
            "--DateFormat", $DateFormat
        )

        if ( $ExportPaths ) {
            $cmdArgList += "--ExportPaths"
            $cmdArgList += (($ExportPaths | Where { Test-Path $_ -PathType Container }) -join ",")
        }



        if ( $Urls ) {
            $cmdArgList += "--Urls"
            $cmdArgList += ($Urls -join ",")
        }
        else {
            $cmdArgList += "--Tenant"
            $cmdArgList += $Global:SPOM_Config.TenantName
        }


        if ( $SkipListsOnlyBlockedByOOBReasons ) { $cmdArgList += "--SkipListsOnlyBlockedByOOBReasons" }
        if ( $SkipUsageInformation ) { $cmdArgList += "--SkipUsageInformation" }
        if ( $SkipUserInformation ) { $cmdArgList += "--SkipUserInformation" }
        if ( $DisableTelemetry ) { $cmdArgList += "--DisableTelemetry" }
        if ( $SkipReport.IsPresent ) { $cmdArgList += "--SkipReport" }


        if ( $PsCmdlet.ParameterSetName -eq "Certificate" ) {

            $Certificate = Get-ChildItem -Path "cert:\CurrentUser\My" -Recurse -ErrorAction SilentlyContinue | Where { $_.HasPrivateKey -and $_.Thumbprint -eq $Thumbprint } | Select -First 1

            if ( ! $Certificate ) {
                Write-Error "Can't find certificate with Thumbprint: $Thumbprint"
            }

            $CertificatePath = Get-Item $Certificate.PSParentPath
            $CertificateStoreName = $CertificatePath.Name
            $CertificateStoreLocation = $CertificatePath.Location

            $cmdArgList += "--ClientId"
            $cmdArgList += $ClientId

            $cmdArgList += "--StoredCertificate"
            $cmdArgList += "{0}|{1}|{2}" -f @($CertificateStoreName, $CertificateStoreLocation, $Thumbprint)

            $cmdArgList += "--AzureTenant"
            $cmdArgList += ("{0}.onmicrosoft.com" -f $Global:SPOM_Config.TenantName)

        }
        elseif ( $PsCmdlet.ParameterSetName -eq "CertificateFile" ) {

            $CertificatePFXItem = Get-Item $CertificatePFX
            $CertificatePFXPasswordPlainText = ([PSCredential]::new(0, $CertificatePFXPassword).GetNetworkCredential().Password)

            $cmdArgList += "--CertificatePFX"
            $cmdArgList += $CertificatePFXItem.FullName

            $cmdArgList += "--CertificatePFXPassword"
            $cmdArgList += $CertificatePFXPasswordPlainText

            $cmdArgList += "--AzureTenant"
            $cmdArgList += ("{0}.onmicrosoft.com" -f $Global:SPOM_Config.TenantName)

        }
        elseif ( $PsCmdlet.ParameterSetName -eq "ClientSecret" ) {

            $cmdArgList += "--ClientId"
            $cmdArgList += $ClientId

            $cmdArgList += "--ClientSecret"
            $cmdArgList += ([PSCredential]::new(0, $ClientSecret).GetNetworkCredential().Password)

        }
        elseif ( $PsCmdlet.ParameterSetName -eq "Credential" ) {

            $cmdArgList += "--User"
            $cmdArgList += $Credential.UserName

            $cmdArgList += "--Password"
            $cmdArgList += $Credential.GetNetworkCredential().Password

        }

        Write-Verbose "$Global:SPModernizationScanner $( $cmdArgList -join " " )"

        & $Global:SPModernizationScanner $cmdArgList


        if ( $OutputFolder -and $ExportPaths -eq $false) {
            Get-ChildItem (($Global:SPModernizationScanner | Get-Item ).DirectoryName) -Directory | Move-Item -Destination (Get-Item $OutputFolder)
        }

    }
}

```

**Comment by jansenbe** [comment]
Using the scanner as module from PS will be complex as you'll receive the reports as streams and you then are responsible for storing them and using them to generate the Excel reports. Think the approach you're currently using (moving the files after the scan ends) is the easiest fix for your problem.

**Comment by jansenbe** [comment]
Hey @Forket , I'm closing this issue as the workaround in your PS wrapper is a good solution.

**Comment by Forket** [comment]
Sure, no problem. Thanks for assistance.
