### ISSUE TITLE
Can't convert SharePoint 2019 on-prem web part from classic to modern

### ISSUE THREAD

**Issue by alekpavlov** [SharePoint/sp-dev-modernization#392]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ x ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ x ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Expected Behavior is to convert classic SharePoint 2019 on-prem web part page to modern

#### Observed Behavior

Converting site...
 Processing Home.aspx
 Modernizing Home.aspx...
ConvertTo-PnPClientSidePage : File Not Found.
At D:\TOOLS\Mapping-2010\Convert-OnPremisesPublishingPages.ps1:131 char:19
+ ...   $result = ConvertTo-PnPClientSidePage -Identity $page.FieldValues[" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPClientSidePage], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage
  Page not transformed, check the logs for issues
 Processing How To Use This Library.aspx
 Modernizing How To Use This Library.aspx...
ConvertTo-PnPClientSidePage : File Not Found.
At D:\TOOLS\Mapping-2010\Convert-OnPremisesPublishingPages.ps1:131 char:19
+ ...   $result = ConvertTo-PnPClientSidePage -Identity $page.FieldValues[" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPClientSidePage], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage
  Page not transformed, check the logs for issues
Script Complete! :)

#### Steps to Reproduce

Could reproduce it any time

#### Submission Guidelines

- If you checked the **"Page Transformation: Error during the use of page transformation from PnP PowerShell"** checkbox then please provide:
  - The output you see in your PowerShell session
  - The output generated by calling `Get-PnPException`
  - The PnP PowerShell version. Run `get-module -Name SharePointPnPPowerShellOnline` and copy the version info
************************************************
Converting site...
 Processing Home.aspx
 Modernizing Home.aspx...
ConvertTo-PnPClientSidePage : File Not Found.
At D:\TOOLS\Mapping-2010\Convert-OnPremisesPublishingPages.ps1:131 char:19
+ ...   $result = ConvertTo-PnPClientSidePage -Identity $page.FieldValues[" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPClientSidePage], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage
  Page not transformed, check the logs for issues
 Processing How To Use This Library.aspx
 Modernizing How To Use This Library.aspx...
ConvertTo-PnPClientSidePage : File Not Found.
At D:\TOOLS\Mapping-2010\Convert-OnPremisesPublishingPages.ps1:131 char:19
+ ...   $result = ConvertTo-PnPClientSidePage -Identity $page.FieldValues[" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPClientSidePage], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage
  Page not transformed, check the logs for issues
Script Complete! :)
************************************************
PS D:\TOOLS\Mapping-2010> Get-PnPException

CorrelationId    : 88c7209f-b0f4-2000-077b-6bc25530e1f1
TimeStampUtc     : 12/12/2019 1:28:16 PM
Message          : File Not Found.
Stacktrace       :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext,
                   Int32 retryCount, Int32 delay, String userAgent)
                      at SharePointPnP.PowerShell.Commands.Base.PipeBinds.PagePipeBind.GetPage(Web web, String listToLoad)
                      at SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 131
************************************************
PS D:\TOOLS\Mapping-2010> get-module -Name SharePointPnPPowerShellOnline

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     3.16.19... SharePointPnPPowerShellOnline       {Add-PnPAlert, Add-PnPApp, Add-PnPClientSidePage, Add-PnPClientSidePageSection...}

PS D:\TOOLS\Mapping-2010>
************************************************

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hi @alekpavlov ,

Can you try to first convert a single web part page. Below is script snippet to get you started (update urls, page folder and page name info):

```PowerShell
# Connect to target SharePoint Online site
$target = Connect-PnPOnline -Url https://contoso.sharepoint.com/sites/modernpagestest -ReturnConnection 

# Connect to source
Connect-PnPOnline https://portal.contoso.com/sites/oldsite -CurrentCredentials

# Update the page name to map your web part page. 
# If the web part page lives outside of the SitePages library then also add -Library "library name" to the commandline
ConvertTo-PnPClientSidePage -Identity "mypage.aspx" -TargetConnection $target -Overwrite -LogType File -LogFolder . -LogVerbose

```
If the transformation starts to run you'll see a .md file being created with log data.

**Comment by alekpavlov** [comment]
Hi @jansenbe ,

that works fine 👍 Because I want to convert a classic page to modern and want it on-premisses, I saved Connect-PnPOnline https://portal.contoso.com/sites/oldsite -CurrentCredentials as $source and in the TargetConnection I used it, so I got a new modern page on-premises in SharePoint 2019.

The problem that I have right now is that for most of the site (migrated from SharePoint 2013 to 2019) the default.aspx page is in the root of the site collection and I'm unable to specify the location of the page, I'm getting "File not found" error. I tried with **_-Library "/"_** but still got an error:
------------------------------
PS D:\TOOLS\Mapping-2010> ConvertTo-PnPClientSidePage -Identity "default.aspx" -TargetConnection $source -Overwrite -LogType File -LogFolder "D:\Tools" -LogVerbose -Library "/"
ConvertTo-PnPClientSidePage : Cannot invoke method or retrieve property from null object. Object returned by the following call stack is null. "GetList
"
At line:1 char:1
+ ConvertTo-PnPClientSidePage -Identity "default.aspx" -TargetConnectio ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPClientSidePage], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage
PS D:\TOOLS\Mapping-2010>
------------------------------

Do you have any suggestion how to specify location when the page is in the root?

Regards
Aleks

**Comment by jansenbe** [comment]
That's good news. For pages living in the root there's a solution: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell#transform-a-pages-that-lives-at-the-root-of-the-site-so-outside-of-a-library

**Comment by alekpavlov** [comment]
Hello @jansenbe ,

When I created a classic page in SharePoint 2019 and then convert it to modern works fine 👍 But in my case I tried to convert migrated classic page from SharePoint 2013 to SharePoint 2019 and I'm getting the error: File not found.

here are some of the messages from ULS log (verbose):

- Returning hr=0x80070002: owssvr.dll: (unresolved symbol, module offset=000000000000AF69)
at 0x00007FFCBF5DAF69 owssvr.dll: (unresolved symbol, module offset=00000000000250DF)
 at 0x00007FFCBF5F50DF Microsoft.SharePoint.Library.ni.dll: (unresolved symbol, module offset=000000000009D01D)
 at 0x00007FFCC6ADD01D

- Unknown SPRequest error occurred. More information: 0x80070002

- System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002), StackTrace:   
 at Microsoft.SharePoint.SPWeb.GetList(String relUrl, SPResourcePath path)    
 at Microsoft.SharePoint.SPWeb.GetList(String strUrl)    
 at Microsoft.SharePoint.ServerStub.SPWebServerStub.InvokeMethod(Object target, String methodName, XmlNodeList xmlargs, ProxyContext proxyContext, Boolean& isVoid)    
 at Microsoft.SharePoint.Client.ServerStub.InvokeMethodWithMonitoredScope(Object target, String methodName, XmlNodeList args, ProxyContext proxyContext, Boolean& isVoid)    
 at Microsoft.SharePoint.Client.ClientMethodsProcessor.InvokeMethod(Object obj, String methodName, XmlNodeList xmlargs, Boolean& isVoid)    
 at Microsoft.SharePoint.Client.ClientMethodsProcessor.GetObjectFromObjectPath(XmlElement xe)    
 at Microsoft.SharePoint.Client.ClientMethodsProcessor.GetObjectFromObjectPathId(String objectPathId)    
 at Microsoft.SharePoint.Client.ClientMethodsProcessor.ProcessInstantiateObjectPath(XmlElement xe)    
 at Microsoft.SharePoint.Client.ClientMethodsProcessor.ProcessStatements(XmlNode xe)    
 at Microsoft.SharePoint.Client.ClientMethodsProcessor.Process()    
 at Microsoft.SharePoint.Client.ClientRequestServiceImpl.ProcessQuery(Stream inputStream, IList`1 pendingDisposableContainer)    
 at Microsoft.SharePoint.Client.ClientRequestService.ProcessQuery(Stream inputStream)    
 at SyncInvokeProcessQuery(Object , Object[] , Object[] )    
 at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)    
 at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)    
 at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)    
 at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)    
 at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)    
 at System.ServiceModel.Dispatcher.ChannelHandler.DispatchAndReleasePump(RequestContext request, Boolean cleanThread, OperationContext currentOperationContext)    
 at System.ServiceModel.Dispatcher.ChannelHandler.HandleRequest(RequestContext request, OperationContext currentOperationContext)    
 at System.ServiceModel.Dispatcher.ChannelHandler.AsyncMessagePump(IAsyncResult result)    
 at System.ServiceModel.Dispatcher.ChannelHandler.OnAsyncReceiveComplete(IAsyncResult result)    
 at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)    
 at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)    
 at System.Runtime.InputQueue`1.AsyncQueueReader.Set(Item item)    
 at System.Runtime.InputQueue`1.EnqueueAndDispatch(Item item, Boolean canDispatchOnThisThread)    
 at System.Runtime.InputQueue`1.EnqueueAndDispatch(T item, Action dequeuedCallback, Boolean canDispatchOnThisThread)    
 at System.ServiceModel.Channels.SingletonChannelAcceptor`3.Enqueue(QueueItemType item, Action dequeuedCallback, Boolean canDispatchOnThisThread)    
 at System.ServiceModel.Channels.HttpPipeline.EnqueueMessageAsyncResult.CompleteParseAndEnqueue(IAsyncResult result)    
 at System.ServiceModel.Channels.HttpPipeline.EnqueueMessageAsyncResult.HandleParseIncomingMessage(IAsyncResult result)    
 at System.Runtime.AsyncResult.SyncContinue(IAsyncResult result)    
 at System.ServiceModel.Channels.HttpPipeline.EmptyHttpPipeline.BeginProcessInboundRequest(ReplyChannelAcceptor replyChannelAcceptor, Action dequeuedCallback, AsyncCallback callback, Object state)    
 at System.ServiceModel.Channels.HttpChannelListener`1.HttpContextReceivedAsyncResult`1.ProcessHttpContextAsync()    
 at System.ServiceModel.Channels.HttpChannelListener`1.BeginHttpContextReceived(HttpRequestContext context, Action acceptorCallback, AsyncCallback callback, Object state)    
 at System.ServiceModel.Activation.HostedHttpTransportManager.HttpContextReceived(HostedHttpRequestAsyncResult result)    
 at System.ServiceModel.Activation.HostedHttpRequestAsyncResult.HandleRequest()    
 at System.ServiceModel.Activation.HostedHttpRequestAsyncResult.BeginRequest()    
 at System.ServiceModel.Activation.HostedHttpRequestAsyncResult.OnBeginRequest(Object state)    
 at System.ServiceModel.AspNetPartialTrustHelpers.PartialTrustInvoke(ContextCallback callback, Object state)    
 at System.ServiceModel.Activation.HostedHttpRequestAsyncResult.OnBeginRequestWithFlow(Object state)    
 at System.Runtime.IOThreadScheduler.ScheduledOverlapped.IOCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)    
 at System.Runtime.Fx.IOCompletionThunk.UnhandledExceptionFrame(UInt32 error, UInt32 bytesRead, NativeOverlapped* nativeOverlapped)    
 at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)  

- Exception occured in scope Microsoft.SharePoint.SPWeb.GetList. Exception=System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)    
 at Microsoft.SharePoint.Library.SPRequestInternalClass.GetMetadataForUrl(String bstrUrl, StorePath spPath, Int32 METADATAFLAGS, Guid& pgListId, Int32& plItemId, Int32& plType, Object& pvarFileOrFolder)    
 at Microsoft.SharePoint.Library.SPRequest.GetMetadataForUrl(String bstrUrl, StorePath spPath, Int32 METADATAFLAGS, Guid& pgListId, Int32& plItemId, Int32& plType, Object& pvarFileOrFolder)    
 at Microsoft.SharePoint.SPWeb.GetList(String relUrl, SPResourcePath path)    
 at Microsoft.SharePoint.SPWeb.GetList(String strUrl)    
 at Microsoft.SharePoint.ServerStub.SPWebServerStub.InvokeMethod(Object target, String methodName, XmlNodeList xmlargs, ProxyContext proxyContext, Boolean& isVoid)    
 at Microsoft.SharePoint.Client.ServerStub.InvokeMethodWithMonitoredScope(Object target, String methodName, XmlNodeList args, ProxyContext proxyContext, Boolean& isVoid)

- Original error: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)    
 at Microsoft.SharePoint.Library.SPRequestInternalClass.GetMetadataForUrl(String bstrUrl, StorePath spPath, Int32 METADATAFLAGS, Guid& pgListId, Int32& plItemId, Int32& plType, Object& pvarFileOrFolder)    
 at Microsoft.SharePoint.Library.SPRequest.GetMetadataForUrl(String bstrUrl, StorePath spPath, Int32 METADATAFLAGS, Guid& pgListId, Int32& plItemId, Int32& plType, Object& pvarFileOrFolder)    
 at Microsoft.SharePoint.SPWeb.GetList(String relUrl, SPResourcePath path)    
 at Microsoft.SharePoint.SPWeb.GetList(String strUrl)    
 at Microsoft.SharePoint.ServerStub.SPWebServerStub.InvokeMethod(Object target, String methodName, XmlNodeList xmlargs, ProxyContext proxyContext, Boolean& isVoid)    
 at Microsoft.SharePoint.Client.ServerStub.InvokeMethodWithMonitoredScope(Object target, String methodName, XmlNodeList args, ProxyContext proxyContext, Boolean& isVoid)

- SocialRESTExceptionProcessingHandler.DoServerExceptionProcessing - SharePoint Server Exception [System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)    
 at Microsoft.SharePoint.Library.SPRequestInternalClass.GetMetadataForUrl(String bstrUrl, StorePath spPath, Int32 METADATAFLAGS, Guid& pgListId, Int32& plItemId, Int32& plType, Object& pvarFileOrFolder)    
 at Microsoft.SharePoint.Library.SPRequest.GetMetadataForUrl(String bstrUrl, StorePath spPath, Int32 METADATAFLAGS, Guid& pgListId, Int32& plItemId, Int32& plType, Object& pvarFileOrFolder)    
 at Microsoft.SharePoint.SPWeb.GetList(String relUrl, SPResourcePath path)    
 at Microsoft.SharePoint.SPWeb.GetList(String strUrl)    
 at Microsoft.SharePoint.ServerStub.SPWebServerStub.InvokeMethod(Object target, String methodName, XmlNodeList xmlargs, ProxyContext proxyContext, Boolean& isVoid)    
 at Microsoft.SharePoint.Client.ServerStub.InvokeMethodWithMonitoredScope(Object target, String methodName, XmlNodeList args, ProxyContext proxyContext, Boolean& isVoid)    
 at Microsoft.SharePoint.Client.ClientMethodsProcessor.InvokeMethod(Object obj, String methodName, XmlNodeList xmlargs, Boolean& isVoid)    
 at Microsoft.SharePoint.Client.ClientMethodsProcessor.GetObjectFromObjectPath(XmlElement xe)    
 at Microsoft.SharePoint.Client.ClientMethodsProcessor.GetObjectFromObjectPathId(String objectPathId)    
 at Microsoft.SharePoint.Client.ClientMethodsProcessor.ProcessInstantiateObjectPath(XmlElement xe)    
 at Microsoft.SharePoint.Client.ClientMethodsProcessor.ProcessStatements(XmlNode xe)    
 at Microsoft.SharePoint.Client.ClientMethodsProcessor.Process()]

Unfortunately I can't send you the all ULS log due to confidential information inside.
I'm using: ConvertTo-PnPClientSidePage -Identity "default.aspx" -TargetConnection $source -Overwrite -LogType File -L
ogFolder "D:\Tools" -LogVerbose -Library "<root>"

**Comment by jansenbe** [comment]
Hey @alekpavlov , do you have time for a debug session? If so please send me your email address to bjansen@microsoft.com and then I'll setup a teams meeting. Please let me know when you've time for  such a session

**Comment by jansenbe** [comment]
Closing as this was about modernizing in-place pages in SP2019 on-premises

**Comment by nicole-ge** [comment]
Hi @jansenbe 

I wann to transform classic blog Page from sp2019 onprem to SPO . I am trying to use the Script from the link you mention. But for me it is not working. It connect to the old Blog post but don't transfer it to SPO. What I should so? Kind regards
