### ISSUE TITLE
Transforming Summary Links to Quick Links Bug

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#74]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

When transforming summary links web part, the tool should cater for values that contain non-json friendly characters.

#### Observed Behavior

Error occurs and stop the transformation for the page - workaround is to remove the characters then transform.

#### Steps to Reproduce

Add summary links web part
Add link in web part with a link, title and a description with a "text" (Speech marks) in the description

#### Additional Information

From Get-PnPException:

Message          : After parsing a value an unexpected character was encountered: L. Path
                   'serverProcessedContent.searchablePlainTexts['items[5].description']', line 1, position 1248.
Stacktrace       :    at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
                      at Newtonsoft.Json.JsonTextReader.Read()
                      at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
                      at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
                      at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
                      at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
                      at OfficeDevPnP.Core.Pages.ClientSideWebPart.SetPropertiesJson(String json)
                      at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1
                   webParts)
                      at SharePointPnP.Modernization.Framework.Transform.PageTransformator.Transform(PageTransformation
                   Information pageTransformationInformation)
                      at SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 61

**Comment by jansenbe** [comment]
Fixed
